name: Release
on:
  push:
    tags:
      - '*'

env:
  PNPM_VERSION: 11.17.0

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install modules
        run: pnpm i

      - name: Publish ${{ github.ref_name }}
        run: pnpm release
        env:
          VERSION: ${{ github.ref_name }}
